### ISSUE TITLE
Create a keyword to start sikuli java process

### ISSUE THREAD

**Issue by rainmanwy** [rainmanwy/robotframework-SikuliLibrary#16]
In current implementation, java process will be started in "**init**". The reason is:
1. RF will scan library and get keyword list(name, argument, doc) when initialize library.

The problems of current implementation are:
1. When library works with RIDE, java process could not be stopped. This is handled by "check whether robot is running", but it is not good enough.
2. When there are multi suites, as scope of library is GLOBAL, library will only be initialized once. If suite 1 "stop remote server", suite 2 will fail.

One proposal is:
1. Add one keyword to start java process.
2. Keep keywords information(name, arguments, doc) in one place(python file?), these information could be stored when library is packaged

**Comment by ChthonicOne** [comment]
I'm going to have to agree with this suggestion. Currently we have the ability to stop the server during a test or suite, but no way to start it up easily as it needs to be running when the script loads imports, but you cannot execute a keyword before you load imports.

The keywords for the library need to be exported to a separate static import, and then we can write a keyword with the process library to start the library server so that the rest of the scripts can execute. Until this is done it is impossible to fully automate the Sikuli Library with the test.

**Comment by rainmanwy** [comment]
Now, when library is inited with mode='NEW'. sikuli java process will not be started. Changes are

- mode "NEW" is introduced, and it will not start sikuli java process. It will not effect old users
- when maven packaging the lib, "keywords.py" file will be created and be packaged to lib. This file will include keywords information(name, doc, args)
- "get_keyword_names", "get_keyword_documentation", "get_keyword_arguments" get info from "keywords.py", not from sikuli java process
- add new keyword "start_sikuli_process" to start sikuli java process in test cases explicitly.

**Comment by jackhao2018** [comment]
hello，When I use the jenkins to call the sikulibrary test (mode=NEW), the following picture always appears, and the use case I run locally and the target machine is normal. This type of start sikuli java process failed! occurs only when called with jenkins.
![W ${I7B~_)L1G3}U_9BYZW](https://user-images.githubusercontent.com/45641639/57745326-4fdafb00-76ff-11e9-9de2-88673f335ccc.png)

thank You

**Comment by ricardo-santiago-alpt** [comment]
@jackhao2018  You could solve the issue?
