### ISSUE TITLE
How to pass Ctrl+A, Shift+Down etc ?

### ISSUE THREAD

**Issue by Raghu6519** [rainmanwy/robotframework-SikuliLibrary#39]
Hi,

i have some scenarios where i need to use combination of two keys, like Ctrl+A, Shift+Down, Shift_Up. 
however the keyword Press Special key accepts only one argument. I have to select all or few lines in a window using above key combinations, how can i achieve it?

Regards,
Raghu

**Comment by rainmanwy** [comment]
@Raghu6519 
Thanks.
i have add a new keyword http://rainmanwy.github.io/robotframework-SikuliLibrary/doc/SikuliLibrary.html#Type%20With%20Modifiers

it will call "type" method in sikuli directly

  /**
   * enters the given text one character/key after another using keyDown/keyUp<br>while holding down the given modifier
   * keys <br>about the usable Key constants see keyDown(keys) <br>Class Key only provides a subset of a US-QWERTY PC
   * keyboard layout<br>the text is entered at the current position of the focus/carret
   *
   * @param text containing characters and/or Key constants
   * @param modifiers constants according to class KeyModifiers
   * @return 1 if possible, 0 otherwise
   */
  public int type(String text, int modifiers)

**Comment by Raghu6519** [comment]
@rainmanwy 

Thanks a lot for your quick response :), this keyword resolves my issue.

**Comment by shippy** [comment]
It seems that this feature hasn't made it to PyPI yet. Are there any plans for updating the library there, @rainmanwy? Is it blocking on anything in particular?

**Comment by rainmanwy** [comment]
I may update pypi later. I am not sure whether travis could do this.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by grandfa8** [comment]
Hi
@rainmanwy can i reproduce case as by as https://answers.launchpad.net/sikuli/+question/200167
I not found respective keyword in documentaion http://rainmanwy.github.io/robotframework-SikuliLibrary/doc/SikuliLibrary.html
