### ISSUE TITLE
Doubt: Highglight and Click

### ISSUE THREAD

**Issue by romuluc** [rainmanwy/robotframework-SikuliLibrary#65]
Previous Highlight keyword follow by Click keyword in same image, crash the click action?

**Comment by rainmanwy** [comment]
Could you give more details?

**Comment by RaiMan** [comment]
the problem is as follows:
In your implementation the highlight feature is not timed. You have to use the clear... keyword, to remove it from the screen again.

Hence in the mentioned situation the first click of the doubleClick removes the highlight (In SikuliX a highlight can be clicked away as long as it is visible) and the second click does what he wants: click the image.

A correct usage would be:
```
Highlight    icon.PNG
#wait some time
Clear All Highlights
Click    icon.PNG
```

IMHO: There is a keyword missing, that represents the timed highlight in SikuliX:
`match.highlight(2)`
which would make the highlight auto-vanish after 2 seconds

**Comment by rainmanwy** [comment]
Thanks @RaiMan, i may add this option here.

**Comment by rainmanwy** [comment]
I have add secs option for highlight.
